set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v143)

set(VCPKG_C_FLAGS_DEBUG "/D_ITERATOR_DEBUG_LEVEL=2")
set(VCPKG_CXX_FLAGS_DEBUG "/D_ITERATOR_DEBUG_LEVEL=2")

# set(VCPKG_C_FLAGS "/D_DISABLE_VECTOR_ANNOTATION")
# set(VCPKG_CXX_FLAGS "/D_DISABLE_VECTOR_ANNOTATION")