/*++

Copyright (C) 2021 Jan Orend

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.6.0.

Abstract: This is an autogenerated C++ implementation file in order to allow easy
development of GladiusLib. It needs to be generated only once.

Interface version: 1.0.0

*/

#include "gladius_abi.hpp"
#include "gladius_gladius.hpp"
#include "gladius_interfaces.hpp"
#include "gladius_interfaceexception.hpp"

using namespace GladiusLib;
using namespace GladiusLib::Impl;

void CWrapper::GetVersion(GladiusLib_uint32 & nMajor, GladiusLib_uint32 & nMinor, GladiusLib_uint32 & nMicro)
{
	nMajor = GLADIUSLIB_VERSION_MAJOR;
	nMinor = GLADIUSLIB_VERSION_MINOR;
	nMicro = GLADIUSLIB_VERSION_MICRO;
}

bool CWrapper::GetLastError(IBase* pInstance, std::string & sErrorMessage)
{
    return pInstance->GetLastErrorMessage(sErrorMessage);
}

void CWrapper::AcquireInstance(IBase* pInstance)
{
	IBase::AcquireBaseClassInterface(pInstance);
}

void CWrapper::ReleaseInstance(IBase* pInstance)
{
	IBase::ReleaseBaseClassInterface(pInstance);
}

IGladius * CWrapper::CreateGladius()
{
    return new CGladius();
}


