/*++

Copyright (C) 2021 Jan Orend

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.6.0.

Abstract: This is an autogenerated CSharp application that demonstrates the
 usage of the CSharp bindings of GladiusLib

Interface version: 1.0.0

*/


using System;
namespace GladiusLib_Example
{
	class GladiusLib_Example
	{
		static void Main()
		{
			try
			{
				UInt32 nMajor, nMinor, nMicro;
				GladiusLib.Wrapper.GetVersion(out nMajor, out nMinor, out nMicro);
				string versionString = string.Format("GladiusLib.version = {0}.{1}.{2}", nMajor, nMinor, nMicro);
				Console.WriteLine(versionString);
			}
			catch (Exception e)
			{
				Console.WriteLine("Exception: \"" + e.Message + "\"");
			}
			Console.WriteLine("Press any key to exit.");
			Console.ReadKey();
		}
	}
}

