/*++

Copyright (C) 2023 Jan Orend

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.6.0.

Abstract: This is an autogenerated C++ Implementation file with the basic internal
 exception type in order to allow an easy use of GladiusLib

Interface version: 1.2.0

*/

#include <string>

#include "gladius_interfaceexception.hpp"

/*************************************************************************************************************************
 Class EGladiusLibInterfaceException
**************************************************************************************************************************/
EGladiusLibInterfaceException::EGladiusLibInterfaceException(GladiusLibResult errorCode)
    : m_errorMessage("GladiusLib Error " + std::to_string(errorCode))
{
    m_errorCode = errorCode;
}

EGladiusLibInterfaceException::EGladiusLibInterfaceException(GladiusLibResult errorCode,
                                                             std::string errorMessage)
    : m_errorMessage(errorMessage + " (" + std::to_string(errorCode) + ")")
{
    m_errorCode = errorCode;
}

GladiusLibResult EGladiusLibInterfaceException::getErrorCode()
{
    return m_errorCode;
}

const char * EGladiusLibInterfaceException::what() const noexcept
{
    return m_errorMessage.c_str();
}
