/*++

Copyright (C) 2023 Jan Orend

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.6.0.

Abstract: This is an autogenerated C++ Header file with the basic internal
 exception type in order to allow an easy use of GladiusLib

Interface version: 1.2.0

*/

#ifndef __GLADIUSLIB_INTERFACEEXCEPTION_HEADER
#define __GLADIUSLIB_INTERFACEEXCEPTION_HEADER

#include <exception>
#include <stdexcept>
#include "gladius_types.hpp"

/*************************************************************************************************************************
 Class EGladiusLibInterfaceException
**************************************************************************************************************************/


class EGladiusLibInterfaceException : public std::exception {
protected:
    /**
    * Error code for the Exception.
    */
    GladiusLibResult m_errorCode;
    /**
    * Error message for the Exception.
    */
    std::string m_errorMessage;

public:
    /**
    * Exception Constructor.
    */
    EGladiusLibInterfaceException(GladiusLibResult errorCode);

    /**
    * Custom Exception Constructor.
    */
    EGladiusLibInterfaceException(GladiusLibResult errorCode, std::string errorMessage);

    /**
    * Returns error code
    */
    GladiusLibResult getErrorCode();
    /**
    * Returns error message
    */
    const char* what() const noexcept override;
};

#endif // __GLADIUSLIB_INTERFACEEXCEPTION_HEADER
