'''++

Copyright (C) 2021 Jan Orend

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.6.0.

Abstract: This is an autogenerated Python application that demonstrates the
 usage of the Python bindings of GladiusLib

Interface version: 1.0.0

'''


import os
import sys
sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), "..", "..", "Bindings", "Python"))
import GladiusLib


def main():
	cwd = os.getcwd()
	origDir = cwd
	os.chdir(cwd + "/../../Implementations/Cpp")
	cwd = os.getcwd()
	print("Current working directory: {0}".format(cwd))
	libpath = cwd
	wrapper = GladiusLib.Wrapper(libraryName = os.path.join(libpath, "gladiuslib"))
	
	major, minor, micro = wrapper.GetVersion()
	print("GladiusLib version: {:d}.{:d}.{:d}".format(major, minor, micro), end="")
	print("")

	gladius = wrapper.CreateGladius()
	gladius.LoadAssembly("D:/gladiusModels/vcore3case/sidepanel_right_hexagon.json")
	for y in range(5):
		for x in range(6):
			gladius.SetFloatParameter("Assembly", "Part_5", "part_col", x)
			gladius.SetFloatParameter("Assembly", "Part_5", "part_row", y)
			filename = origDir + "/tile_{}_{}.stl".format(x, y)
			gladius.ExportSTL(filename)
			print("After Export col : {}  row: {}".format(gladius.GetFloatParameter("Assembly", "Part_5", "part_col"), gladius.GetFloatParameter("Assembly", "Part_5", "part_row")))



if __name__ == "__main__":
	try:
		main()
	except GladiusLib.EGladiusLibException as e:
		print(e)
